apiVersion: v1
kind: Service
metadata:
  name: overthink-service
  labels:
    app: overthink-engine
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    app: overthink-engine
